sudo: false
language: python
cache: pip
python:
  - "3.5"
env:
  global:
    - COVERALLS_PARALLEL=true
    - MIXED=0
    - BATCHED=0
  matrix:
    include:
      - python: 3.5
        env: BACKEND=gaussian
      - python: 3.5
        env: BACKEND=gaussian MIXED=1
      - python: 3.5
        env: BACKEND=fock
      - python: 3.5
        env: BACKEND=fock MIXED=1
      - python: 3.5
        env: BACKEND=tf
      - python: 3.5
        env: BACKEND=tf MIXED=1
      - python: 3.5
        env: BACKEND=tf BATCHED=1
      - python: 3.5
        env: BACKEND=tf MIXED=1 BATCHED=1
        sudo: required
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install wheel codecov
  - python3 setup.py bdist_wheel
  - pip install dist/StrawberryFields*.whl
# command to run tests
script:
  - coverage3 run -m unittest discover tests
after_success:
  - codecov -F $BACKEND,m$MIXED,b$BATCHED
notifications:
  slack: xanaduhq:IjuNiD7j36slp7NqRdWuQq1O
